#! /bin/sh

usage() {
   echo "Usage : "
   echo "$0 <channel number>"
}

if [ $# -ne 1 ] ; then
   usage
   exit -1
fi

channel=$1

gst-launch-1.0 heliostvsrc uri="$1" host="localhost" ! \
tsdemux name=d \
d. ! queue max-size-bytes=0 max-size-time=0 ! mpegvideoparse ! decodebin ! videoconvert ! videoscale ! autovideosink \
d. ! queue max-size-bytes=0 max-size-time=0 ! mpegaudioparse ! decodebin ! audioconvert ! autoaudiosink
